/**
 * Where each agent the `skills` CLI supports looks for project skills, relative
 * to the repository root. Mirrored by hand from skills@1.7.2, which publishes
 * no API for it, so a newer agent needs an entry before it can be named.
 *
 * Agents on `.agents/skills` read the shared folder directly; any other
 * gets a link from its own folder into the shared one.
 */
export const AGENT_SKILLS_DIRS: Readonly<Record<string, string>> = {
  adal: '.adal/skills',
  'aider-desk': '.aider-desk/skills',
  amp: '.agents/skills',
  antigravity: '.agents/skills',
  'antigravity-cli': '.agents/skills',
  astrbot: 'data/skills',
  augment: '.augment/skills',
  'autohand-code': '.autohand/skills',
  bob: '.bob/skills',
  'claude-code': '.claude/skills',
  cline: '.agents/skills',
  'codearts-agent': '.codeartsdoer/skills',
  codebuddy: '.codebuddy/skills',
  codemaker: '.codemaker/skills',
  codestudio: '.codestudio/skills',
  codex: '.agents/skills',
  'command-code': '.commandcode/skills',
  continue: '.continue/skills',
  cortex: '.cortex/skills',
  crush: '.crush/skills',
  cursor: '.agents/skills',
  deepagents: '.agents/skills',
  devin: '.devin/skills',
  dexto: '.agents/skills',
  droid: '.agents/skills',
  eve: 'agent/skills',
  firebender: '.agents/skills',
  forgecode: '.forge/skills',
  fx: '.fx/skills',
  'gemini-cli': '.agents/skills',
  'github-copilot': '.agents/skills',
  goose: '.goose/skills',
  grok: '.grok/skills',
  'hermes-agent': '.hermes/skills',
  'iflow-cli': '.iflow/skills',
  'inference-sh': '.inferencesh/skills',
  jazz: '.jazz/skills',
  junie: '.junie/skills',
  kilo: '.agents/skills',
  kimchi: '.kimchi/skills',
  'kimi-code-cli': '.agents/skills',
  'kiro-cli': '.kiro/skills',
  kode: '.kode/skills',
  lingma: '.lingma/skills',
  loaf: '.agents/skills',
  mcpjam: '.mcpjam/skills',
  'minimax-code': '.minimax/skills',
  'mistral-vibe': '.vibe/skills',
  moxby: '.moxby/skills',
  mux: '.mux/skills',
  neovate: '.neovate/skills',
  ona: '.ona/skills',
  openclaw: 'skills',
  opencode: '.agents/skills',
  openhands: '.openhands/skills',
  pi: '.agents/skills',
  pochi: '.pochi/skills',
  'posit-assistant': '.posit/assistant/skills',
  promptscript: '.agents/skills',
  qoder: '.qoder/skills',
  'qoder-cn': '.qoder/skills',
  'qwen-code': '.qwen/skills',
  reasonix: '.reasonix/skills',
  replit: '.agents/skills',
  roo: '.roo/skills',
  rovodev: '.rovodev/skills',
  'sarvam-code': '.agents/skills',
  'tabnine-cli': '.tabnine/agent/skills',
  terramind: '.terramind/skills',
  tinycloud: '.tinycloud/skills',
  trae: '.trae/skills',
  'trae-cn': '.trae/skills',
  universal: '.agents/skills',
  warp: '.agents/skills',
  windsurf: '.windsurf/skills',
  zcode: '.zcode/skills',
  zed: '.agents/skills',
  zencoder: '.zencoder/skills',
  zenflow: '.zencoder/skills',
}

export const SHARED_SKILLS_DIR = '.agents/skills'
